### PR TITLE
Changed the color to colorPrimaryDark

### LINKED ISSUE #40: Change Color of Navigation Bar to colorPrimaryDark
**Describe the chore**
Change the color

**Would you like to work on the issue?**
- [ ] Yes
- [x] No
- Other:

### PR DESCRIPTION
**Pull request by goyal9314**
Fixes #40 

Changes:   android:background="?attr/colorPrimaryDark"

### CODE REVIEW

**Comment by amdal07** [comment]
@goyal9314 add a screenshot

**Comment by goyal9314** [comment]
Screenshot_1559117919

**Comment by somenath1435** [comment]
@goyal9314 refer https://stackoverflow.com/questions/27839105/android-lollipop-change-navigation-bar-color

**Comment by somenath1435** [comment]
@goyal9314 add new screen shot

**Comment by goyal9314** [comment]
Screenshot_1559126989

**Pull request merged**
