### PR TITLE
Add Team Fragment

### LINKED ISSUE #26: Add TeamFragment
**Describe the feature you'd like to add**
Add page containing list of SAAR team members
**Would you like to work on the issue?**
- [x] Yes
- [ ] No
- Other:

### PR DESCRIPTION
**Pull request by oindrilabhadra78**
Fixes #26

Changes: Team Fragment added containing names and images of team members

Screenshots for the change:
WhatsApp Image 2019-05-18 at 19 01 25

### CODE REVIEW

**Comment by somenath1435** [comment]
@oindrilabhadra78 image of raghu is wrong

**Comment by somenath1435** [comment]
@oindrilabhadra78 remove hardcoded text in fragment_team.xml

**Comment by oindrilabhadra78** [comment]
> @oindrilabhadra78 image of raghu is wrong

Image of raghu was not available

**Comment by oindrilabhadra78** [comment]
> @oindrilabhadra78 remove hardcoded text in fragment_team.xml

@amdal07 Put your views

**Comment by somenath1435** [comment]
@oindrilabhadra78 please provide full page screenshots

**Pull request merged**
