### PR TITLE
fix: Added About Us page

### LINKED ISSUE #21: Add About Us Page
**Describe the feature you'd like to add**
Add About Us page
**Would you like to work on the issue?**
- [x] Yes
- [ ] No
- Other:

### PR DESCRIPTION
**Pull request by somenath1435**
Fixes #21 

Changes: Added About Us page similar to https://saar.iitp.ac.in

Screenshots for the change:

ze

### CODE REVIEW

**Comment by atm1504** [comment]
@somenath1435 please change the card colors. Check out the website, how a simple card background has been used. Please try to do something like that. : )

**Comment by amdal07** [comment]
@somenath1435 make the relevant changes asap. Also resolve the conflict from your side

**Comment by amdal07** [comment]
@somenath1435 resolve the conflicts

**Comment by somenath1435** [comment]
@amdal07 Pr is updated

**Pull request merged**
