### PR TITLE
Updated the TeamFragment.Java.

### LINKED ISSUE #31: Add Facebook intent to every committee member photo
**Describe the feature you'd like to add**
Add Facebook intent in each photo of team members. Clicking on each team member photo should redirect to the Facebook account of that member.

**Would you like to work on the issue?**
Any newbies can take it.

### PR DESCRIPTION
**Pull request by Ashgo18**
Fixes #31 

Changes: Added Facebook intent on each team member's ImageView and Toast for those whose Profile doesn't exist in TeamFragment.Java.

### CODE REVIEW

**Comment by Ashgo18** [comment]
@amdal07  Yaah , Everyone's profile is working .

**Comment by amdal07** [comment]
@Ashgo18 remember to add screenshot when u make any make any change related to ui or feature enhancement.

**Comment by amdal07** [comment]
@Ashgo18 good job. Carry on

**Comment by Ashgo18** [comment]
Screenshots Updated  .

**Pull request merged**
